# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил:
- Пчелкин Дмитрий Андреевич
- ПИЭ-21-2

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы - это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто "возьмёт их из этого декоратора"). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи. P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

```python
from functools import lru_cache


@lru_cache(None) # декоратор динамического программирования
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n -2)

                                        
if __name__ == '__main__':
    print(fibonacci(100))
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/lab1.png)

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func


@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138, 15, 48, 2)
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/lab2.png)

## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')


if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/lab3.png)

## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться "Успешная регистрация"

```python
class NegativeValueException(Exception):
    pass


def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')


if __name__ == '__main__':
    name = '12345678910'
    check_name(name)
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/lab4.png)

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: init () (вызывается при создании класса декоратора в программе) и call () (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')


@SiteChecker
def site():
    print('Усердная работа сайта')


if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/lab5.png)


## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:
def fibonacci():
fib1 = fib2 = 1
for i in range(2, 200):
fib1, fib2 = fib2, fib1 + fib2
print(fib2, end='")
name==main
fibonacci()
### Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы. Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.

```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"\nФункция {func.__name__} выполнялась {execution_time} секунд")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end='')

if __name__ == "__main__":
    fibonacci()

```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/sam1.png)

## Выводы

Данный код представляет собой декоратор timing_decorator, который измеряет время выполнения функции. Функция fibonacci реализует расчет 200-го числа Фибоначчи и выводит его значение. Декоратор используется для измерения времени выполнения fibonacci. Когда программа запускается, она выводит значение 200-го числа Фибоначчи и время, затраченное на выполнение функции.

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение ("бросить исключение") и вывести в консоль "файл пустой", а если он не пустой, то вывести информацию из файла.

```python
def read_file(file_path):
    try:
        with open(file_path, 'r') as file:
            data = file.read()
            if not data:
                raise Exception("Файл пустой")
            else:
                print("Информация из файла:")
                print(data)
    except FileNotFoundError:
        print("Файл не найден")
    except Exception as e:
        print(e)

empty_file_path = "empty_file.txt"
with open(empty_file_path, 'w'):
    pass

non_empty_file_path = "non_empty_file.txt"
with open(non_empty_file_path, 'w') as file:
    file.write("info")

read_file(empty_file_path)
read_file(non_empty_file_path)
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/sam2.png)

## Выводы

Данный код определяет функцию read_file, которая читает содержимое файла по указанному пути. В случае возникновения ошибок (например, файл не найден или пуст), функция выводит соответствующие сообщения. Затем создаются два файла: "empty_file.txt" (пустой) и "non_empty_file.txt" (с содержимым "info"). Функция read_file вызывается для обоих файлов, демонстрируя обработку различных сценариев, таких как обнаружение пустого файла и вывод его содержимого, а также успешное чтение и вывод содержимого непустого файла. 
  
## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка "Неподходящий тип данных. Ожидалось число.". Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
def add_two_and_input():
    try:
        user_input = input("Введите число: ")
        result = 2 + float(user_input)
        print(f"Результат сложения 2 и введенного числа: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

add_two_and_input()
add_two_and_input()
add_two_and_input()
add_two_and_input()
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/sam3.png)

## Выводы

Данный код определяет функцию add_two_and_input, которая запрашивает у пользователя ввод числа, пытается сложить его с 2, и выводит результат. Если введенные данные не являются числом, программа обрабатывает исключение ValueError и выводит соответствующее сообщение. Функция вызывается четыре раза для демонстрации обработки различных вариантов ввода от пользователя. 
  
## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class CustomDecorator:
    # Инициализация декоратора
    def __init__(self, func):
        self.func = func

    # Реализация вызова декоратора
    def __call__(self, *args, **kwargs):
        print(f"До выполнения функции {self.func.__name__}")
        # Вызов оригинальной функции
        result = self.func(*args, **kwargs)
        print(f"После выполнения функции {self.func.__name__}")
        return result

# Функция 1: умножение
@CustomDecorator
def multiply(a, b):
    result = a * b
    print(f"Результат умножения: {result}")
    return result

# Функция 2: возведение в степень
@CustomDecorator
def power(base, exponent):
    result = base ** exponent
    print(f"Результат возведения в степень: {result}")
    return result

# Тесты
multiply(3, 4)
power(2, 3)
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/sam4.png)

## Выводы

Данный код определяет класс-декоратор CustomDecorator, который выводит сообщения до и после выполнения функции, к которой он применяется. Декоратор используется для двух функций: умножения (multiply) и возведения в степень (power). При вызове этих функций, декоратор выводит сообщения до и после выполнения каждой функции, демонстрируя свою реализацию вызова. 
  
## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class CustomException(Exception):
    def __init__(self, message="Произошла ошибка"):
        self.message = message
        super().__init__(self.message)

# Использование исключения при делении на ноль
def divide_numbers(a, b):
    try:
        if b == 0:
            raise CustomException("Деление на ноль недопустимо")
        result = a / b
        print(f"Результат деления: {result}")
    except CustomException as ce:
        print(f"Ошибка: {ce}")

# Использование исключения при вводе отрицательного числа
def get_positive_number():
    try:
        number = int(input("Введите положительное число: "))
        if number < 0:
            raise CustomException("Введено отрицательное число")
        print(f"Введенное положительное число: {number}")
    except CustomException as ce:
        print(f"Ошибка: {ce}")

# Тесты
divide_numbers(10, 0)
get_positive_number()
```

### Результат.
![Меню](https://github.com/krafenn/Software_Engineering/blob/Tema10/Tema10/pic/sam5.png)

## Выводы

Данный код определяет пользовательское исключение CustomException, которое выводит сообщение об ошибке при его возникновении. Затем использует это исключение в двух фрагментах кода: divide_numbers, который обрабатывает деление на ноль, и get_positive_number, который обрабатывает ввод отрицательного числа. Программа демонстрирует вызов обоих функций с недопустимыми входными данными и выводит соответствующие сообщения об ошибках. 

## Общие выводы по теме

В данной теме я познакомился с декораторами и исключениями языка Python.
